#define _GNU_SOURCE  1
#define BAUTH_SUPPORT 1
#define DAUTH_SUPPORT 1
#define EPOLL_SUPPORT 0
#define HAVE_ARPA_INET_H 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_DECL_SOCK_NONBLOCK 0
#define HAVE_DECL_TCP_CORK 0
#define HAVE_DECL_TCP_NOPUSH 1
#define HAVE_DLFCN_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FSEEKO 1
#define HAVE_GCRYPT_H 1
#define HAVE_INET6 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBCURL 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_MATH_H 1
#define HAVE_MEMMEM 1
#define HAVE_MEMORY_H 1
#define HAVE_MESSAGES 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_OPENSSL_ENGINE_H 1
#define HAVE_OPENSSL_ERR_H 1
#define HAVE_OPENSSL_EVP_H 1
#define HAVE_OPENSSL_PEM_H 1
#define HAVE_OPENSSL_RAND_H 1
#define HAVE_OPENSSL_RSA_H 1
#define HAVE_OPENSSL_SHA_H 1
#define HAVE_POLL 1
#define HAVE_POLL_H 1
#define HAVE_POSTPROCESSOR 1
#define HAVE_PTHREAD_H 1
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_SEARCH_H 1
#define HAVE_SOCKADDR_IN_SIN_LEN 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_MSG_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1
#define HTTPS_SUPPORT 1
#define LIBCURL_FEATURE_ASYNCHDNS 1
#define LIBCURL_FEATURE_IPV6 1
#define LIBCURL_FEATURE_LIBZ 1
#define LIBCURL_FEATURE_NTLM 1
#define LIBCURL_FEATURE_SSL 1
#define LIBCURL_PROTOCOL_DICT 1
#define LIBCURL_PROTOCOL_FILE 1
#define LIBCURL_PROTOCOL_FTP 1
#define LIBCURL_PROTOCOL_FTPS 1
#define LIBCURL_PROTOCOL_HTTP 1
#define LIBCURL_PROTOCOL_HTTPS 1
#define LIBCURL_PROTOCOL_IMAP 1
#define LIBCURL_PROTOCOL_LDAP 1
#define LIBCURL_PROTOCOL_POP3 1
#define LIBCURL_PROTOCOL_RTSP 1
#define LIBCURL_PROTOCOL_SMTP 1
#define LIBCURL_PROTOCOL_TELNET 1
#define LIBCURL_PROTOCOL_TFTP 1
#define LT_OBJDIR ".libs/"
#define MHD_REQ_CURL_GNUTLS_VERSION "2.8.6"
#define MHD_REQ_CURL_NSS_VERSION "3.12.0"
#define MHD_REQ_CURL_OPENSSL_VERSION "0.9.8"
#define MHD_REQ_CURL_VERSION "7.16.4"
#define MHD_USE_POSIX_THREADS 1
#define OSX 1
#define PACKAGE "libmicrohttpd"
#define PACKAGE_BUGREPORT "libmicrohttpd@gnu.org"
#define PACKAGE_NAME "libmicrohttpd"
#define PACKAGE_TARNAME "libmicrohttpd"
#define PACKAGE_URL ""
#define SPDY_SUPPORT 1
#define STDC_HEADERS 1
#define VERSION "0.9.42"
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
# endif
#endif
#ifndef _DARWIN_USE_64_BIT_INODE
# define _DARWIN_USE_64_BIT_INODE 1
#endif
#define _MHD_EXTERN __attribute__((visibility("default"))) extern
