#!/usr/bin/env bash
set -e

function each() {
    sed -e $'/^\tpath = /!d;s///' .gitmodules | sort
}

each | while read -r sub; do (
    cd "${sub}"
    git fetch -v
) done

declare -A head

function tag() {
    head[$1]=$(cd "$1" && git tag -l | grep -P '^'"$2"'$' | tail -n 1)
    echo "${head[$1]}"
}

head[app-shared/engine]=$(cat app-shared/flutter/bin/internal/engine.version)
head[app-shared/flutter]=2.0.4
head[env/libcxx]=origin/release_90
head[env/libcxxabi]=origin/release_90
tag p2p/boost 'boost-[0-9.]*'
tag min-webrtc/abseil-cpp '[0-9].*'
tag min-webrtc/openssl 'OpenSSL_[0-9_]*[a-z]'
head[min-krypton/vpn-libraries]=origin/main
head[p2p/ctre]=origin/main
head[srv-shared/GSL]=v2.1.0

each | while read -r sub; do (
    cd "${sub}"
    echo
    echo "${sub}"
    git log --color --graph --format=oneline HEAD...${head[${sub}]-origin/master} || echo $sub
) done | less -R

# url is stuck due to https://forums.developer.apple.com/thread/120977 :/
# (I tried to use a local copy of libcxx on Apple, but crashed on iOS 14)

# to upgrade zlib I need to upgrade base and build; the new base is using
# features from libcxx after what I have, so I need to move to llvm embed

# icu is stuck due to v8 using an internal: ListFormatter::createInstance
# GSL is stuck due to cpp-libp2p using the stupid cmake "hunter" thing :/
