#!/usr/bin/env bash
set -e

git submodule foreach 'git fetch -v && git remote set-head origin -a'

declare -A head

function tag() {
    head[$1]=$(cd "$1" && git tag -l --sort=version:refname | grep -P '^'"$2"'$' | tail -n 1)
    echo "${head[$1]}"
}

tag p2p/boost 'boost-[0-9.]*'
tag min-openssl/openssl 'OpenSSL_[0-9_]*[a-z]'
tag p2p/sqlite 'version-[0-9.]*'

# to upgrade to a later version of libc++ would require LLVM as submodule
head[env/libcxx]=origin/release_90
head[env/libcxxabi]=origin/release_90

head[app-shared/flutter]=3.13.0
head[app-shared/engine]=$(cat app-shared/flutter/bin/internal/engine.version)

# pcre2 is stuck due to https://github.com/PCRE2Project/pcre2/issues/205

# url is stuck due to https://forums.developer.apple.com/thread/120977 :/
# (I tried to use a local copy of libcxx on Apple, but crashed on iOS 14)
head[p2p/url]=7c822cb9873b1422e09be5131f30e9d83d487096

git submodule foreach -q 'echo $displaypath' | while read -r sub; do (
    cd "${sub}"
    echo
    echo "${sub}"
    git log --color --graph --format=oneline HEAD..${head[${sub}]-origin/HEAD} || echo $sub
) done | less -R
