//
// Do not modify: Generated by generate-assets.sh.
//
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/svg.dart';

class OrchidAsset {
  static final svg = OrchidAssetSvg();
  static final image = OrchidAssetImage();
  static final token = OrchidAssetSvgToken();
  static final chain = OrchidAssetSvgChain();
}

class OrchidAssetImage {
  OrchidAssetImage();

  static const background_glow_path = 'assets/images/Background_Glow.png';
  final background_glow = Image.asset(background_glow_path);
  static const crt_lines_path = 'assets/images/CRT_Lines.png';
  final crt_lines = Image.asset(crt_lines_path);
  static const crt_lines_blue_path = 'assets/images/CRT_Lines_blue.png';
  final crt_lines_blue = Image.asset(crt_lines_blue_path);
  static const crt_lines_purple_path = 'assets/images/CRT_Lines_purple.png';
  final crt_lines_purple = Image.asset(crt_lines_purple_path);
  static const logo_neon_stroke_path = 'assets/images/Logo_Neon_Stroke.png';
  final logo_neon_stroke = Image.asset(logo_neon_stroke_path);
  static const logo_outline_path = 'assets/images/Logo_Outline.png';
  final logo_outline = Image.asset(logo_outline_path);
  static const assignment_path = 'assets/images/assignment.png';
  final assignment = Image.asset(assignment_path);
  static const business_path = 'assets/images/business.png';
  final business = Image.asset(business_path);
  static const logo_path = 'assets/images/logo.png';
  final logo = Image.asset(logo_path);
  static const logo_glow_path = 'assets/images/logo_glow.png';
  final logo_glow = Image.asset(logo_glow_path);
  static const logo_small_purple_path = 'assets/images/logo_small_purple.png';
  final logo_small_purple = Image.asset(logo_small_purple_path);
  static const map_pin_path = 'assets/images/map_pin.png';
  final map_pin = Image.asset(map_pin_path);
  static const path_path = 'assets/images/path.png';
  final path = Image.asset(path_path);
  static const qrcode_path = 'assets/images/qrcode.png';
  final qrcode = Image.asset(qrcode_path);
  static const scan_path = 'assets/images/scan.png';
  final scan = Image.asset(scan_path);
  static const settings_path = 'assets/images/settings.png';
  final settings = Image.asset(settings_path);
  static const world_map_path = 'assets/images/world_map.png';
  final world_map = Image.asset(world_map_path);
}

class OrchidAssetImage3x {
  OrchidAssetImage3x();

  static const background_glow_path = 'assets/images/3.0x/Background_Glow.png';
  final background_glow = Image.asset(background_glow_path);
  static const crt_lines_path = 'assets/images/3.0x/CRT_Lines.png';
  final crt_lines = Image.asset(crt_lines_path);
  static const crt_lines_blue_path = 'assets/images/3.0x/CRT_Lines_blue.png';
  final crt_lines_blue = Image.asset(crt_lines_blue_path);
  static const crt_lines_purple_path = 'assets/images/3.0x/CRT_Lines_purple.png';
  final crt_lines_purple = Image.asset(crt_lines_purple_path);
  static const logo_neon_stroke_path = 'assets/images/3.0x/Logo_Neon_Stroke.png';
  final logo_neon_stroke = Image.asset(logo_neon_stroke_path);
  static const logo_outline_path = 'assets/images/3.0x/Logo_Outline.png';
  final logo_outline = Image.asset(logo_outline_path);
  static const assignment_path = 'assets/images/3.0x/assignment.png';
  final assignment = Image.asset(assignment_path);
  static const business_path = 'assets/images/3.0x/business.png';
  final business = Image.asset(business_path);
  static const logo_path = 'assets/images/3.0x/logo.png';
  final logo = Image.asset(logo_path);
  static const logo_glow_path = 'assets/images/3.0x/logo_glow.png';
  final logo_glow = Image.asset(logo_glow_path);
  static const logo_small_purple_path = 'assets/images/3.0x/logo_small_purple.png';
  final logo_small_purple = Image.asset(logo_small_purple_path);
  static const map_pin_path = 'assets/images/3.0x/map_pin.png';
  final map_pin = Image.asset(map_pin_path);
  static const path_path = 'assets/images/3.0x/path.png';
  final path = Image.asset(path_path);
  static const qrcode_path = 'assets/images/3.0x/qrcode.png';
  final qrcode = Image.asset(qrcode_path);
  static const settings_path = 'assets/images/3.0x/settings.png';
  final settings = Image.asset(settings_path);
  static const thin_path = 'assets/images/3.0x/thin.png';
  final thin = Image.asset(thin_path);
  static const world_map_path = 'assets/images/3.0x/world_map.png';
  final world_map = Image.asset(world_map_path);
}

class OrchidAssetSvg {
  OrchidAssetSvg();

  static const access_time_path = 'assets/svg/access_time.svg';
  final access_time = SvgPicture.asset(access_time_path);
  static const delete_icon_path = 'assets/svg/delete_icon.svg';
  final delete_icon = SvgPicture.asset(delete_icon_path);
  static const document_path = 'assets/svg/document.svg';
  final document = SvgPicture.asset(document_path);
  static const dollars_icon_path = 'assets/svg/dollars_icon.svg';
  final dollars_icon = SvgPicture.asset(dollars_icon_path);
  static const ethereum_path = 'assets/svg/ethereum.svg';
  final ethereum = SvgPicture.asset(ethereum_path);
  static const gauge_icon_path = 'assets/svg/gauge_icon.svg';
  final gauge_icon = SvgPicture.asset(gauge_icon_path);
  static const hops_icon_path = 'assets/svg/hops_icon.svg';
  final hops_icon = SvgPicture.asset(hops_icon_path);
  static const inspector_icon_path = 'assets/svg/inspector_icon.svg';
  final inspector_icon = SvgPicture.asset(inspector_icon_path);
  static const openvpn_path = 'assets/svg/openvpn.svg';
  final openvpn = SvgPicture.asset(openvpn_path);
  static const orchid_logo_side_path = 'assets/svg/orchid_logo_side.svg';
  final orchid_logo_side = SvgPicture.asset(orchid_logo_side_path);
  static const orchid_logo_small_path = 'assets/svg/orchid_logo_small.svg';
  final orchid_logo_small = SvgPicture.asset(orchid_logo_small_path);
  static const orchid_logo_text_path = 'assets/svg/orchid_logo_text.svg';
  final orchid_logo_text = SvgPicture.asset(orchid_logo_text_path);
  static const payments_path = 'assets/svg/payments.svg';
  final payments = SvgPicture.asset(payments_path);
  static const price_path = 'assets/svg/price.svg';
  final price = SvgPicture.asset(price_path);
  static const privacy_path = 'assets/svg/privacy.svg';
  final privacy = SvgPicture.asset(privacy_path);
  static const qr_scan_path = 'assets/svg/qr_scan.svg';
  final qr_scan = SvgPicture.asset(qr_scan_path);
  static const scan_path = 'assets/svg/scan.svg';
  final scan = SvgPicture.asset(scan_path);
  static const settings_gear_path = 'assets/svg/settings_gear.svg';
  final settings_gear = SvgPicture.asset(settings_gear_path);
  static const share_path = 'assets/svg/share.svg';
  final share = SvgPicture.asset(share_path);
  static const toggle_checked_path = 'assets/svg/toggle_checked.svg';
  final toggle_checked = SvgPicture.asset(toggle_checked_path);
  static const toggle_unchecked_path = 'assets/svg/toggle_unchecked.svg';
  final toggle_unchecked = SvgPicture.asset(toggle_unchecked_path);
  static const traffic_path = 'assets/svg/traffic.svg';
  final traffic = SvgPicture.asset(traffic_path);
  static const wireguard_path = 'assets/svg/wireguard.svg';
  final wireguard = SvgPicture.asset(wireguard_path);
  static const xdai_path = 'assets/svg/xdai.svg';
  final xdai = SvgPicture.asset(xdai_path);
}

class OrchidAssetSvgChain {
  OrchidAssetSvgChain();

  static const arbitrum_chain_path = 'assets/svg/chains/arbitrum-chain.svg';
  final arbitrum_chain = SvgPicture.asset(arbitrum_chain_path);
  static const binance_smart_chain_path = 'assets/svg/chains/binance-smart-chain.svg';
  final binance_smart_chain = SvgPicture.asset(binance_smart_chain_path);
  static const celo_chain_path = 'assets/svg/chains/celo-chain.svg';
  final celo_chain = SvgPicture.asset(celo_chain_path);
  static const gnossis_chain_path = 'assets/svg/chains/gnossis-chain.svg';
  final gnossis_chain = SvgPicture.asset(gnossis_chain_path);
  static const near_aurora_chain_path = 'assets/svg/chains/near-aurora-chain.svg';
  final near_aurora_chain = SvgPicture.asset(near_aurora_chain_path);
  static const neon_evm_chain_path = 'assets/svg/chains/neon-evm-chain.svg';
  final neon_evm_chain = SvgPicture.asset(neon_evm_chain_path);
  static const optimism_chain_path = 'assets/svg/chains/optimism-chain.svg';
  final optimism_chain = SvgPicture.asset(optimism_chain_path);
  static const ronin_chain_path = 'assets/svg/chains/ronin-chain.svg';
  final ronin_chain = SvgPicture.asset(ronin_chain_path);
  static const rsk_chain_path = 'assets/svg/chains/rsk-chain.svg';
  final rsk_chain = SvgPicture.asset(rsk_chain_path);
  static const unknown_chain_path = 'assets/svg/chains/unknown-chain.svg';
  final unknown_chain = SvgPicture.asset(unknown_chain_path);
}

class OrchidAssetSvgToken {
  OrchidAssetSvgToken();

  static const avalanche_avax_token_path = 'assets/svg/tokens/avalanche-avax-token.svg';
  final avalanche_avax_token = SvgPicture.asset(avalanche_avax_token_path);
  static const binance_coin_bnb_token_path = 'assets/svg/tokens/binance-coin-bnb-token.svg';
  final binance_coin_bnb_token = SvgPicture.asset(binance_coin_bnb_token_path);
  static const bitcoin_btc_token_path = 'assets/svg/tokens/bitcoin-btc-token.svg';
  final bitcoin_btc_token = SvgPicture.asset(bitcoin_btc_token_path);
  static const celo_token_path = 'assets/svg/tokens/celo-token.svg';
  final celo_token = SvgPicture.asset(celo_token_path);
  static const clover_clv_token_path = 'assets/svg/tokens/clover-clv-token.svg';
  final clover_clv_token = SvgPicture.asset(clover_clv_token_path);
  static const ethereum_classic_etc_token_path = 'assets/svg/tokens/ethereum-classic-etc-token.svg';
  final ethereum_classic_etc_token = SvgPicture.asset(ethereum_classic_etc_token_path);
  static const ethereum_eth_token_path = 'assets/svg/tokens/ethereum-eth-token.svg';
  final ethereum_eth_token = SvgPicture.asset(ethereum_eth_token_path);
  static const fantom_ftm_token_path = 'assets/svg/tokens/fantom-ftm-token.svg';
  final fantom_ftm_token = SvgPicture.asset(fantom_ftm_token_path);
  static const fuse_token_path = 'assets/svg/tokens/fuse-token.svg';
  final fuse_token = SvgPicture.asset(fuse_token_path);
  static const huobi_ht_token_path = 'assets/svg/tokens/huobi-ht-token.svg';
  final huobi_ht_token = SvgPicture.asset(huobi_ht_token_path);
  static const klay_token_path = 'assets/svg/tokens/klay-token.svg';
  final klay_token = SvgPicture.asset(klay_token_path);
  static const matic_token_path = 'assets/svg/tokens/matic-token.svg';
  final matic_token = SvgPicture.asset(matic_token_path);
  static const moonbeam_glmr_token_path = 'assets/svg/tokens/moonbeam-glmr-token.svg';
  final moonbeam_glmr_token = SvgPicture.asset(moonbeam_glmr_token_path);
  static const moonriver_movr_token_path = 'assets/svg/tokens/moonriver-movr-token.svg';
  final moonriver_movr_token = SvgPicture.asset(moonriver_movr_token_path);
  static const okt_token_path = 'assets/svg/tokens/okt-token.svg';
  final okt_token = SvgPicture.asset(okt_token_path);
  static const orchid_oxt_token_path = 'assets/svg/tokens/orchid-oxt-token.svg';
  final orchid_oxt_token = SvgPicture.asset(orchid_oxt_token_path);
  static const poa_token_path = 'assets/svg/tokens/poa-token.svg';
  final poa_token = SvgPicture.asset(poa_token_path);
  static const telos_tlos_token_path = 'assets/svg/tokens/telos-tlos-token.svg';
  final telos_tlos_token = SvgPicture.asset(telos_tlos_token_path);
  static const unknown_token_path = 'assets/svg/tokens/unknown-token.svg';
  final unknown_token = SvgPicture.asset(unknown_token_path);
  static const xdai_token_path = 'assets/svg/tokens/xdai-token.svg';
  final xdai_token = SvgPicture.asset(xdai_token_path);
}

