#!/bin/bash
set -e
make target=sim app "$@"
xcrun simctl install booted out-sim/Payload/Orchid.app

name=$(grep '^name' ../identity.mk | sed 's/^.*:=[ ]*\([^ ]\{1,\}\).*/\1/')
domain=$(grep '^domain' ../identity.mk | sed 's/^.*:=[ ]*\([^ ]\{1,\}\).*/\1/')
app="${domain}.${name}"
xcrun simctl launch booted "$app"
