#!/bin/bash
set -e
env/solc.sh 0.5.13 build lottery.sol --evm-version istanbul
cpp -C -P -DORC_ERC=0 lottery1.sol >lottery1-eth.sol
env/solc.sh 0.7.1 build lottery1-eth.sol --evm-version istanbul --optimize --optimize-runs 10000
cpp -C -P -DORC_ERC=1 lottery1.sol >lottery1-tok.sol
env/solc.sh 0.7.1 build lottery1-tok.sol --evm-version istanbul --optimize --optimize-runs 10000
