#!/bin/bash

here=$(which "$0")
if test -L "${here}"; then
    here=$(readlink "${here}")
fi
here=${here%/*}

case "$1" in
    (--atleast-pkgconfig-version) ;;
    (--version) echo 0.29.2;;
    (*) exit 1; ;;
esac
