#!/bin/bash

here=$(which "$0")
if test -L "${here}"; then
    here=$(readlink "${here}")
fi
here=${here%/*}

args=()
for arg in "$@"; do case "${arg}" in
    (--print-errors);;
    (--short-errors);;
    (*) args+=("${arg}")
esac; done

echo "${args[*]}" >>/tmp/pkg-config.log

case "${args[*]}" in
    ("--atleast-pkgconfig-version "*) ;;
    ("--version") echo 0.29.2;;

    ("--exists libpng") ;;
    ("--libs libpng") echo "-lpng16 -lz";;

    ("--exists pixman-1 >= 0.36.0") ;;

    ("--libs --cflags nettle hogweed")
        variable=NETTLE_${ENV_ARCH//-/_}
        echo "${!variable}"
    ;;

    ("--modversion nettle hogweed")
        version=$(sed -e '/^AC_INIT(\[nettle\], \[/!d;s///;s/\].*//' "${here}/../p2p/nettle/configure.ac")
        echo "${version}"
        echo "${version}"
    ;;

    (*) exit 1; ;;
esac
