#!/bin/bash

here=$(which "$0")
if test -L "${here}"; then
    here=$(readlink "${here}")
fi
here=${here%/*}

case "$*" in
    (--atleast-pkgconfig-version) ;;
    (--version) echo 0.29.2;;

    ("--libs --cflags nettle hogweed")
        variable=NETTLE_${ENV_ARCH//-/_}
        echo "${!variable}"
    ;;

    ("--modversion nettle hogweed")
        version=$(sed -e '/^AC_INIT(\[nettle\], \[/!d;s///;s/\].*//' "${here}/../p2p/nettle/configure.ac")
        echo "${version}"
        echo "${version}"
    ;;

    (*) exit 1; ;;
esac
