name: CI
on: [push]
jobs:

  cache-submodule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: env/setup.sh
    - uses: ./.github/actions/submodule

  build-lnx-mac:
    needs: [cache-submodule]
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - run: env/setup.sh
    - uses: ./.github/actions/submodule

    - uses: ./.github/actions/nerdctl
    - run: env/setup-ndk.sh

    - run: gmake -j3 -C srv-daemon target=lnx

    - uses: actions/upload-artifact@v4
      with:
        name: orchidd-lnx-amd64
        path: srv-daemon/out-lnx/x86_64/orchidd

