name: CI
on: [push]
jobs:

  homebrew-pkgconf:
    runs-on: macos-latest

    steps:
    - run: brew unlink pkg-config@0.29.2 || true
    - run: brew install pkg-config
    - run: brew unlink pkg-config@0.29.2

    - run: false
    - run: brew update
    - run: brew update
    - run: brew upgrade
    - run: brew uninstall openssl@1.1
    - run: brew uninstall ruby@3.0
    - run: brew cleanup
    - run: cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f
    - run: brew config
    - run: brew doctor
    - run: brew update
